### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by shawnps-sigsci** [sergi/go-diff#101]
Hi, would it be possible to get a new tagged release? There are quite a lot of changes in master which aren't in a release:

https://github.com/sergi/go-diff/compare/1744e2970ca51c86172c8190fadad617561ed6e7..da645544ed44df016359bd4c0e3dc60ee3a0da43

Thank you for making this library!

**Comment by shawnps-sigsci** [comment]
Hello, any thoughts on this?

**Comment by sergi** [comment]
Done, now at v1.1.0
