### ISSUE TITLE
How to tell percent different

### ISSUE THREAD

**Issue by vbisbest** [sergi/go-diff#109]
Thoughts on determining how different two files are?  Say we compare file1.txt to file2.txt and I would like to see that they are 90% similar.   Is that something I can determine with this current library or something that would need to be added?  Thanks!

**Comment by habdank** [comment]
IMHO this is not precisely defined requirement. What means files have 0%, 50% or 90% similarity?
Generally the library provides you very good metric, which is Levenstein distance. 
With this one you can measure how documents differs.

**Comment by sergi** [comment]
I agree with @habdank. Providing the percentage of difference is beyond the scope of this library.
