### ISSUE TITLE
Is this repo still maintained? Friendly fork?

### ISSUE THREAD

**Issue by twpayne** [sergi/go-diff#134]
Thank you for this code. I'm a very happy user of `sergi/go-diff`, although I have to pin my use of the module to the latest working version, i.e. [`v1.1.0`](https://github.com/sergi/go-diff/releases/tag/v1.1.0).

Is this repo still maintained? There are many [open issues with no response](https://github.com/sergi/go-diff/issues), the most recent tagged version ([v1.2.0](https://github.com/sergi/go-diff/releases/tag/v1.2.0)) has been broken (#123) for a year and half, and there have been [no commits to `master` for a similar time period](https://github.com/sergi/go-diff/commits/master). There are [many pull requests that have had no response](https://github.com/sergi/go-diff/pulls).

Under the terms of [`sergi/go-diff`'s MIT license](https://github.com/sergi/go-diff/blob/master/LICENSE), I propose to friendly fork this repo, unless there is still an intent to work on this. Go needs a good diff library like this, and a friendly fork is one that is carefully designed to be easy to merge back into the original.

Let me know if there is still an intent to work on this valuable software, or if I should fork.

**Comment by glahdou** [comment]
@twpayne It does seem like it is worth making a friendly fork so we continue maintaining this valuable project.

Given the MIT license, is it a typical practice to fork the project so that we save it  and continue maintenance ?

I would be happy to be a contributor for maintenance and improvements.

**Comment by glahdou** [comment]
@sergi

**Comment by twpayne** [comment]
Closing due to the [release of 1.3.1](https://github.com/sergi/go-diff/releases/tag/v1.3.1).
