### ISSUE TITLE
A bug in DiffText1

### ISSUE THREAD

**Issue by tkf** [sergi/go-diff#29]
With some texts, DiffText1 returns a wrong result. An example of such data is dmp.go of revision b94bf7 and b94bf7^. To see this, get text1.go (which just prints DiffText1) from https://gist.github.com/tkf/12bde871bf794e59bea88b659ed5b95b and run it as:

``` sh
cd PATH/TO/go-diff/diffmatchpatch
diff <(go run PATH/TO/text1.go <(git show 'b94bf7:./dmp.go') <(git show 'b94bf7^:./dmp.go')) <(git show 'b94bf7:./dmp.go')
```

which pints

``` diff
471c471
<
---
>                                       break
658c658
<
---
>
```

i.e., `dmp.DiffText1(diffs) != text1`.

The above gist also includes `text1.bash` which automates finding such examples. For example, I found many such examples by running:

``` sh
git clone https://go.googlesource.com/go
cd go/src
PATH/TO/text1.bash **/*.go > examples
```

**Comment by jeremejevs** [comment]
There is `DiffTimeout = 0` commented out in the Gist. Which version of `text1.go` did you run, with timeout of `time.Hour` or `0`?

**Comment by zimmski** [comment]
Along the way, this got fixed. I tested this with the version you were probably using  bc2ef1260ca6e3888a54bae1bd3260b0aae53e52 and then with master:
```bash
$ git checkout bc2ef1260ca6e3888a54bae1bd3260b0aae53e52
$ go install ./...
$ diff <(go run text1.go <(git show 'b94bf7:./diffmatchpatch/dmp.go') <(git show 'b94bf7^:./diffmatchpatch/dmp.go')) <(git show 'b94bf7:./diffmatchpatch/dmp.go')
471c471
< 
---
>                                       break
658c658
< 
---
> 
$ git checkout master
$ go install ./...
$ diff <(go run text1.go <(git show 'b94bf7:./diffmatchpatch/dmp.go') <(git show 'b94bf7^:./diffmatchpatch/dmp.go')) <(git show 'b94bf7:./diffmatchpatch/dmp.go')
```

Master does not output anything for your test case.

**Comment by zimmski** [comment]
Thanks for reporting this! I will add a test case if there isn't already one.

**Comment by zimmski** [comment]
The problem is only triggered with checklines=true
