### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by zimmski** [sergi/go-diff#33]
@sergi  I am wondering if this project is dead?

**Comment by client9** [comment]
I'm happy to work on a fork.  Anyone interesting in helping?

**Comment by zimmski** [comment]
@client9: I am hesitating to make a fork because of the many problems that a fork entails. This repository has already ~200 stars. So it might be already well established. I would rather contribute to this repository by reviewing PRs, cleaning up and doing some enhancements here and there. So my plan would be to ask the original maintainer for his permission. What do you think?

**Comment by client9** [comment]
Oh yes @zimmski    If you can become an owner and keep this repo working, then that is best.  If not, then we need to do something else.

**Comment by zimmski** [comment]
Since the owner seems unresponsive on GitHub, I will try to contact him via his mail address.

**Comment by zimmski** [comment]
@client9: @sergi has accepted me as the second maintainer of go-diff. I will work on the following items starting this week:
- Reworking the repository to use TravisCI and Coveralls
- Reworking the repository to add build checks for gofmt, golint and govet
- Work down all open PRs
- Work down all open issues
- Reworking the repositories code without breaking the API
+- Including renaming and moving files around
+- Updating the README to be more user and contributor friendly
+- Converting the existing tests to solely table-driven tests
+- Splitting the code to be more maintainable
- Try to make the repository more contribution attractive

I would be very happy if you could help out by reviewing at least my code PRs. I am also open for any ideas on what could be done without breaking the API.

**Comment by client9** [comment]
hi @zimmski  I've been busy traveling.   Good job!
I'm happy to help in any way you want.

**Comment by zimmski** [comment]
@client9: I have sufficient rights now but I will be in meeting for next 2-3 days. Will work on go-diff the rest of the week though. If you have any changes I would be happy to review them :-)

**Comment by zimmski** [comment]
@client9 could you please take a look at #50. It is the first step of refactoring the repository since I am pretty much done with everything else.
