### ISSUE TITLE
Bring coverage up to 100% line coverage

### ISSUE THREAD

**Issue by zimmski** [sergi/go-diff#55]
There are some lines that still do not have test cases https://coveralls.io/github/sergi/go-diff It would be nice to bring the coverage up to a real 100% and then stay there by making decreasing coverage a PR failure.

**Comment by maksimov** [comment]
I'm learning Go and I thought the best way to do it would be to improve some tests. I brought coverage up a notch from 99.3% to 99.4%, but then I started experimenting with a test for patch.go:546 and I've added this test-case (_never mind the expected value, I was going to correct it_):
`{"@@ -0,0 +0,0 @@\n+abc\n", "Bad patch mode"} `

Now my test fails like this:

```--- FAIL: TestPatchFromText (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1398840]

goroutine 51 [running]:
testing.tRunner.func1(0xc4201c40e0)
	/usr/local/go/src/testing/testing.go:644 +0x55d
panic(0x13f3de0, 0x1620fb0)
	/usr/local/go/src/runtime/panic.go:489 +0x2ee
github.com/maksimov/go-diff/diffmatchpatch.TestPatchFromText(0xc4201c40e0)
	/Users/stas/Fun/TryGo/src/github.com/maksimov/go-diff/diffmatchpatch/patch_test.go:81 +0xb90
testing.tRunner(0xc4201c40e0, 0x145ace8)
	/usr/local/go/src/testing/testing.go:679 +0x229
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:716 +0x53d
```
Do you think it's a genuine candidate for code improvement or am I being silly with my test case?
Thanks!

**Comment by maksimov** [comment]
Yes, I guess it's my test case. The panic is in the test code.

**Comment by zimmski** [comment]
I did not try it but when I guess that the test panics because "err" is nil so the "Error" call fails because of that. I think it is NEVER silly to improve a project ;-) To be honest, if you are just learning Go it would be more fun to write new code than adding test cases. Finding test cases for this project is especially hard, there aren't many instances left and the easy ones are already gone.

**Comment by zimmski** [comment]
Maybe https://github.com/sergi/go-diff/issues/54 is more fun since you would write new code, must test it, and then have to benchmark your solution. The marker is here https://github.com/sergi/go-diff/blob/431343a89a2ec4ea8168b3ee3d7a96169f6ff605/diffmatchpatch/diff.go#L459 But beware that if the solution has a bad benchmark, we cannot merge it.

**Comment by zimmski** [comment]
I looked through the open issues and I think https://github.com/sergi/go-diff/issues/49 could be also mildly interesting since the whole project is missing example for every exported API endpoint. #57 and #58 could be also interesting, at least there is new code involved. However, if you are just learning Go I am a little lost on what might be the most interesting and easiest issue for this project.

**Comment by maksimov** [comment]
Thanks very much for your help, @zimmski! I'll try a few things and see how I get on.

**Comment by zimmski** [comment]
@maksimov I think with your changes the bar has been raised high enough to close this issue
