### ISSUE TITLE
lint.sh is broken on macOS 10.8+ due to a different version of grep

### ISSUE THREAD

**Issue by maksimov** [sergi/go-diff#64]
OSX have switched from GNU grep to BSD grep in version 10.8 and for this reason `grep -P` is no longer supported. 

There is a workaround to install pcre grep, which will install GNU grep and -P will work again:
`brew install grep --with-default-names`

Another solution is to change `grep -P` to a relevant perl command, details can be found [here](http://stackoverflow.com/questions/16658333/grep-p-no-longer-works-how-can-i-rewrite-my-searches).

**Comment by zimmski** [comment]
I see that "-E" is supported as well, let's go with that?

**Comment by maksimov** [comment]
Yep, it seems to work. 👍 
I've only tried `-e` so far and it didn't.

**Comment by zimmski** [comment]
`-e` is the argument for the search pattern itself, `-E` is to select the matcher which interprets those patterns. I am glad that this works with MacOSX I have no way of testing with that OS :crying_cat_face:
