### ISSUE TITLE
Add a CI builder for MacOSX

### ISSUE THREAD

**Issue by zimmski** [sergi/go-diff#65]
I know that TravisCI has MacOSX support, but I did not look into that yet.

**Comment by maksimov** [comment]
I can look into this, but do you think I can use a workaround from #64 there or do you want to fix it properly with perl or some other way?

**Comment by zimmski** [comment]
I would prefer grep instead of perl because I am not sure if perl is included in every OS, especially if this should work under Windows too.

**Comment by maksimov** [comment]
Gotcha. I will have a look for other possible ways to do it with grep to avoid workarounds, but should they be unavoidable I'll go with that. Thanks.
