### ISSUE TITLE
Check for the exact error class in all tests

### ISSUE THREAD

**Issue by zimmski** [sergi/go-diff#71]
Checks like the following must be refactored
```go
_, err = dmp.DiffFromDelta("", "+%c3%xy")
if err == nil {
	assert.Fail(t, "expected Invalid URL escape.")
}
```

The problem is that we only check that the error is not nil, but we do not check for the error class. This means that any error lets the test pass even though it is possible that it was the wrong error.

One way to test for the error class is to simply check if assert.Contains if a part of the error string can be found. Another one is to add special error types, and another one is to use one of many encapsulating error packages.

**Comment by maksimov** [comment]
Found this a little odd when I was extending the tests. I might have a swing at that.
