### ISSUE TITLE
why is the body of the patch excaped with %xx notation?

### ISSUE THREAD

**Issue by kyoh86** [sergi/go-diff#87]
Is it specification of the GNU diff?
I want get simple diffs like below.

```
@@ -24,21 +24,22 @@
 ve.

-[Not] eat to eat.
+[Not] live to eat.
```

But in fact, I'll get below.

```
@@ -24,21 +24,22 @@
 ve.%0A
-%5BNot%5D eat to eat.
+%5BNot%5D live to eat.
```

**Comment by zegkljan** [comment]
Has there been any progress on this? Is it possible to turn off this escaping?

**Comment by alvardes** [comment]
I have also encountered this problem. The generated patches are incorrect because of the URL escaping the lines. 

It seems that the escaping is done because "google does it like this" in some of their library: https://github.com/sergi/go-diff/pull/24#issuecomment-257103612

**Comment by kyoh86** [comment]
@sergi Is this project dead?

**Comment by sergi** [comment]
No, not dead. It's complete. The behavior above is consistent with Google's diffmatchpatch library, which this library is based on.

**Comment by sergi** [comment]
That being said, I admit I need to do some maintenance and probably release a new version during this weekend!

**Comment by timbunce** [comment]
I've just encountered this problem as well. Would you accept a PR for it @sergi?

**Comment by kyoh86** [comment]
This may be dead project

**Comment by sergi** [comment]
@timbunce I’d be happy to accept a PR if you’re still up for it!

**Comment by timbunce** [comment]
Perhaps just document the current behaviour so it's not an unpleasant surprise, and suggest calling url.QueryUnescape() on the output. (I'm not sure if that's perfect workaround, but it's been sufficient for us.)

**Comment by kyoh86** [comment]
I'll use go-cmp instead. bye.
