### ISSUE TITLE
Inconsistent results when the patches have special characters

### ISSUE THREAD

**Issue by nihlaakram** [sergi/go-diff#97]
When the patches have special characters such as %, > and < , inconsistent patch status is returned by PatchApply()

**Comment by ernierasta** [comment]
Hi, I know almost nothing about this library, but from what I tested, those symbols will not occur in patch if You use `DiffMain` and then `PatchMake` functions. they will be converted to:
%25, %3E and %3C in patch string.

If you are creating patch in some different way maybe consider converting those chars to given values.
